project:
  type: book
  output-dir: docs #docs _book

book:
  title: "Survival Course: scRNA‑seq + CITE‑seq"
  site-url: https://eveliacoss.github.io/Workshop2026_scRNAseq_CITEseq_libro/
  author: 
    - name: Thais Crippa de Oliveira
      degrees: PhD
      url: https://portal.edat.unicamp.br/perfil?origem=&docente=332656&sigla_unidade=&nome_unidade=&nome_programa=
      orcid: https://orcid.org/0000-0002-9959-0690
      email: crippathais@gmail.com 
      affiliations:
        - name: UNICAMP
          country: Brasil
    - name: Evelia Coss
      degrees: PhD
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: Mexico
          url: https://www.enesjuriquilla.unam.mx/
  
  date: "07/02/2026"
  page-navigation: true
  chapters:
    - index.qmd
    - cap1_repaso.qmd
    - cap2_resources.qmd
    - cap3_aboutDataset.qmd
    - cap4_course.qmd
    - notas.qmd
  # Information
  repo-url: https://github.com/EveliaCoss/Workshop2026_scRNAseq_CITEseq_libro # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "enesLogo.png" # icono de la pagina en pestana


format:
  html:
    toc-depth: 4
    number-depth: 3
    # css
    css: styles.css
    linkcolor: "#007f99"
    
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

babelquarto:
  languagecodes:
  - name: es
    text: "Español"
  - name: pt
    text: "Português"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es', 'pt']
title-es: "Curso de supervivencia: scRNA-seq + CITE-se"
title-pt: "Curso de sobrevivencia: scRNA-seq + CITE-seq"
author-es: 
    - name: Thais Crippa de Oliveira
      degrees: Dra.
      url: https://portal.edat.unicamp.br/perfil?origem=&docente=332656&sigla_unidade=&nome_unidade=&nome_programa=
      orcid: https://orcid.org/0000-0002-9959-0690
      email: crippathais@gmail.com 
      affiliations:
        - name: UNICAMP
          country: Brasil
    - name: Evelia Coss
      degrees: Dra.
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: México
          url: https://www.enesjuriquilla.unam.mx/
author-pt: 
    - name: Thais Crippa de Oliveira
      degrees: Dra.
      url: https://portal.edat.unicamp.br/perfil?origem=&docente=332656&sigla_unidade=&nome_unidade=&nome_programa=
      orcid: https://orcid.org/0000-0002-9959-0690
      email: crippathais@gmail.com 
      affiliations:
        - name: UNICAMP
          country: Brasil
    - name: Evelia Coss
      degrees: Dra.
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: México
          url: https://www.enesjuriquilla.unam.mx/
lang: en

