# About Dataset

## gse149689_subset_3k

## Paper: An immunophenotype-coupled transcriptomic atlas of human hematopoietic progenitors

Nature immunology: <https://www.nature.com/articles/s41590-024-01782-4#data-availability> 

Raw sequencing FASTQ files and the processed HDF5 (h5) matrix have been deposited in the Gene Expression Omnibus database under accession code [GSE245108](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE245108). CITE-seq data generated by Pei et al. were accessed via the accession ID [GSE232559](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE232559). All imputed Infinity Flow objects are available in the FlowRepository under ID [FR-FCM-Z6UQ](http://flowrepository.org/id/FR-FCM-Z6UQ). An interactive web portal with the associated Azimuth instance and data visualization tools is available at <https://altanalyze.org/MarrowAtlas/>. Interactive data visualization and analysis tools for the CITE-seq bone marrow single-cell datasets are provided at <https://altanalyze.org/MarrowAtlas/>. [Source data](https://www.nature.com/articles/s41590-024-01782-4#Sec33) are provided with this paper.\

- CITE-seq <https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE245108>

- scRNA-seq <https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE232559>

- Github: <https://github.com/nsalomonis/Human-Bone-Marrow-Titration-Atlas>

NOTAS: ADD image. Info Sobre el dataset (tipo de células o tejidos, Número de células detectadas, tecnología, secuenciador, plataforma, genoma usado para el alineamiento, versión de cell ranger) (D5 <https://eveliacoss.github.io/Workshop_scRNAseq_presentacion/Clase2_Normalizacion.html#5> )
